### ISSUE TITLE
Voting - Slider Scale

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Zapit2me#10]
- slider "scale" - needs a mod() algorithm so numbers display intermittently (on the axis)

From @yasirkhan177 
"i did fixes for client side .. for bar chart .. but for pie , i checked lot of options but didn't yet find a better way. "

**Comment by cjcornell** [comment]
I would like to find a way to 
- start the sliding scale at 0  (instead of 1) - prefer to start at 0 for the default.
- adjust the "mod" (so that we can adjust how often a label is displayed) ... I am OK doing this in code - and not in the admin platform, as long as it is documented in the code.

**Comment by yasirkhan177** [comment]
ok

**Comment by yasirkhan177** [comment]
set by default to 0 ( starting sliding scale value ) .....


and in  /clientforms/voting.php  <<<< on line **** 222 ****  .. HAVE inserted the  comments with details..


In simple word .. you need to change step value  ... for example if  you set step = 20 .... and scale range is  0-100 ... then it will show label (integer) after every 20 numbers.  in this case labels will be .... 0    20    40    60   80   100 ......

**Comment by yasirkhan177** [comment]
we can also handle step value via database in the future ,if you want .. for example .. voting_range=0-100;30  <<<< second parameter can be set as step value and if left blank than automatic scaling will be applied

**Comment by cjcornell** [comment]
almost perfect - but we need the charts to reflect exactly the same thing ...
so - at the very least, can you set the chart the same way and document the way you just did for the client

**Comment by cjcornell** [comment]
Address my last comment and 8.6 is done!

**Comment by yasirkhan177** [comment]
charts are only set by horizontal bar or vertical scroll bar . i already documented it in voting_chart.php

**Comment by cjcornell** [comment]
I meant that charts should have the same range (and increment) as the corresponding client form.

**Comment by yasirkhan177** [comment]
just showing you demo for slider chart display .. i can fix it more  after your confirmation

**Comment by cjcornell** [comment]
not sure what you mean.  client slider starts at 0 and increments 0-30-90-120  
chart is 1-31-61-91-121 ...
I wanted them the same (perhaps using a a class or something where it onlyneeds to be changed in 1 place?

**Comment by yasirkhan177** [comment]
charts doesn't start with zero .. that's why it shows 1-31-61 .......

**Comment by cjcornell** [comment]
I was hoping you can start to see (on your own, without me typing detailed
detailed explanations!)  why certain features look bad or good.  like this
one....
can u understand why the chart scale needs to look like the forms scale?

**Comment by yasirkhan177** [comment]
because demonstrator (admin) will show the result to audience .. and if both scales are same then it will not be confusing. 

highcharts has limitations .. i will still search on it ,and will let you know if i come up with better solution

**Comment by cjcornell** [comment]
OK - a better solution - not a harder solution.
hard to believe that highcharts x-axis display cannot start at 0  - very hard to believe

**Comment by yasirkhan177** [comment]
i'm not saying it from my side.. i'm saying what i have read. but i'm still not 100% sure. that's why i said ,i will still search on it .

**Comment by yasirkhan177** [comment]
you can check it now .. on zapit2.me

**Comment by cjcornell** [comment]
Looks good - but does the axis/scaling need to be adjusted in 2 places (form and chart) if we want to change it?

**Comment by yasirkhan177** [comment]
yes .. but we can do this via database as well ,will need to add new field in script_table or can utilize one of existing fields ..

**Comment by cjcornell** [comment]
definitely don't want to add a new field!
but you could add a new parameter in client_extra_parameters and chart_extra_parameters for   slider_x_axis_increment=30  and slider_x_axis_origin=0

**Comment by yasirkhan177** [comment]
slider_x_axis_origin=0 << its fixed from the x programmer code.. so i don't think if we need to take care of it in future .. but doesn't need at least for now .. 

slider_x_axis_increment=30 <<< this will be address

**Comment by cjcornell** [comment]
OK - do this and we'll be done with phase 8.6
Though don't forget to document this someplace ... 
since in an upcoming milestone I want you to document zapit2me  (the parameters etc - not user doc)

**Comment by yasirkhan177** [comment]
ok
