### ISSUE TITLE
Voting Forms - Ability to add comments

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Zapit2me#5]
Ability to add comments, contact info (specifically with the form) for each "vote"	

Option/Parameter.If "comments=ON" (or other param) then an input UI appears below the voting area. the user can enter text and submit with vote. Later, a chart option will to display the comments & also give option to tweet/FB post the comment.			

From @yasirkhan177 
if script_table->client_extra_paramenter=true << if that field value is = true .... than comment button will be displayed otherwise not. i will recheck my approach and will try to do it with ajax ,will be more elegant

CJ -

**Comment by cjcornell** [comment]
Note 1.
The embedded parameter method is not correct  (ie  >client_extra_paramenter=true....  ) wow .. bad.  we use this field for MANY other parameters!!
Instead, you need either to create a new field for this parameter OR detect  "user_comment=true"  inside the client_extra_paramenter  field.

Note 2.
This needs to work for Multi-voting form(s) too.

**Comment by yasirkhan177** [comment]
Note 2.
This needs to work for Multi-voting form(s) too. <<< including in this milestone or you making sure for future?

**Comment by cjcornell** [comment]
it is on the roadmap spreadsheet - though it was not prominent to see.  because of this I will move it to a followup milestone

**Comment by cjcornell** [comment]
so - Note 1 is the only part required to complete this task

**Comment by yasirkhan177** [comment]
client_extra_parameter=comments=on  <<<< other client parameters can be separated by comma (,)......

**Comment by cjcornell** [comment]
OK - will test shortly.  
BTW - Log all these parameters etc some place.  Later I will ask you to document it as a new milestone.  (generally the parameters and the forms)

**Comment by cjcornell** [comment]
slight bug.
I tested in script table-.screen_id=42  (voting slider) 
client_extra_parameter  already had "true" in it  .. which I forget what this was suppose to do!
but I added so it read: 

true,
comments=on

and it did not work

but when I reversed it
comments=on,
true

it worked OK

**Comment by yasirkhan177** [comment]
actually you will not give any space or new line.. if you are >>> true,comments=on  or in any order .. it will work

**Comment by cjcornell** [comment]
OK thanks... i figure it was something simple.
what does "true" do?

**Comment by yasirkhan177** [comment]
true has nothing to do .. its just can be anything .. i mean as you told me ... extra_client_parameters may contain some other parameters .. so i just put something dummy ... 

you can remove this "true"
